### ISSUE TITLE
Poly line

### ISSUE THREAD

**Issue by robertpassaro** [gsarig/ootb-openstreetmap#2]
I saw your roadmap on the blog post about this project (https://www.gsarigiannidis.gr/wordpress-gutenberg-map-block-openstreetmap/)

Another possible future feature (because of a specific need for a project I'm working on :) would be the ability to draw a route (polyline) on a map, as opposed to just pins.

I was thinking of actually playing around with this to see what I can do. If you are interested in having another person contribute to this and maybe someday leave you a pull request, would you share your package.json/package-lock.json just to speed up tooling.

This is a fantastic project. You are doing this right. Thank you!

**Comment by gsarig** [comment]
Hi @robertpassaro 
Sorry for the delayed response, I accidentally muted the notifications for the project (I didn't have much activity anyway so I never checked) and I didn't see your message for a long time. I've just updated the project to include package.json and package-lock.json. 

Thanks!

**Comment by gsarig** [comment]
Hi @robertpassaro 
It took me more than 2 years, but the plugin now has support for both polylines and polygons. 

See more info and demos on the [release notes of version 2.1.0](https://github.com/gsarig/ootb-openstreetmap/releases/tag/2.1.0).
