### ISSUE TITLE
Leaflet gesture handling

### ISSUE THREAD

**Issue by sebfried** [gsarig/ootb-openstreetmap#23]
https://github.com/Raruto/leaflet-gesture-handling

**Comment by gsarig** [comment]
Hi @sebfried Can you elaborate more on that? Which specific problems/bugs would this plugin solve?

**Comment by sebfried** [comment]
Hi @gsarig It's similar to the gesture handling that is used by Google Maps. If, for example, the map is very big, you can get stuck, especially on mobile phones. I implemented the plugin on videomat.org, where you can check it out.

**Comment by gsarig** [comment]
Thanks @sebfried I see what you mean, and I agree that this should be addressed. I'm putting it in my roadmap, and, in fact, high in the priorities, as it might not be considered a bug, but it can be annoying on specific designs.

**Comment by gsarig** [comment]
@sebfried This has been deployed with v.2.4.0: https://github.com/gsarig/ootb-openstreetmap/releases/tag/2.4.0
Thanks for reporting it.
