### ISSUE TITLE
Fix for CloudFlare Rocket Loader

### ISSUE THREAD

**Issue by Hoerli1337** [gsarig/ootb-openstreetmap#29]
Currently, the plugin does not work with the Rocket Loader from CloudFlare.
As far as this is active, the plugin is no longer loaded on the page.

As long as the page is not yet published and only a logged in person with sufficient rights is editing the page, the map will load without any problems.
At this point CloudFlare does not intervene yet.

Maybe this info page will help:
[CloudFlare - Ignore JavaScripts in Rocket Loader](https://developers.cloudflare.com/fundamentals/speed/rocket-loader/ignore-javascripts/)

**Comment by gsarig** [comment]
Hi,
The plugin loads its scripts using [wp_enqueue_script](https://developer.wordpress.org/reference/functions/wp_enqueue_script/), which is the suggested way to do so in WordPress. Adding special configuration for 3rd-party tools is out of scope, but I believe that you should be able to fix this issue by utilizing the [scrpit_loader_tag](https://developer.wordpress.org/reference/hooks/script_loader_tag/) hook with something like that:

```
function ootb_add_data_attribute( $tag, $handle, $src ) {
    if ( 'ootb-openstreetmap' !== $handle )
       return $tag;

    return str_replace( ' src', ' data-cfasync="false" src', $tag );
}

add_filter( 'script_loader_tag', 'ootb_add_data_attribute', 10, 3 );

```
Placing the above code on your theme's `functions.php` should add the additional attribute to tell Rocket Loader to ignore the script.
