### ISSUE TITLE
Complianz with Out of the Block: OpenStreetMap

### ISSUE THREAD

**Issue by n-langle** [gsarig/ootb-openstreetmap#32]
Hi, 

I recently open an [issue](https://github.com/Really-Simple-Plugins/complianz-gdpr/issues/405) on Complianz repo. 
We detected an error in ootb-openstreetmap when OpenStreetMap is blocked by Complianz.

Is it possible to support Complianz on your side as recommended by Complianz developers ?

WordPress: 5.9.7
Complianz Privacy Suite (GDPR/CCPA) premium multisite: 6.4.3
Out of the Block: OpenStreetMap: 2.4.0 

Best regards

**Comment by gsarig** [comment]
Hi @n-langle I did a quick test locally, and saw that if you add `data-category="functional"` to the script, it will load. To do so, you can paste this to your theme's `functions.php`:

```
function add_data_attribute($tag, $handle) {
    if ('ootb-openstreetmap' !== $handle) {
        return $tag;
    }
    return str_replace('<script ', '<script data-category="functional" ', $tag);
}
add_filter('script_loader_tag', 'add_data_attribute', 10, 2);
```

**Comment by n-langle** [comment]
Hi @gsarig,
Thanks for your response, I will test that.
