### ISSUE TITLE
Adding map style

### ISSUE THREAD

**Issue by frietboer** [gsarig/ootb-openstreetmap#42]
Great plugin so far!

It would be great to be able to add map style to a block. Maybe by adding a Mapbox style url? In our case it would even be preferable to add this by a filter in functions.php. So all maps would have the same style.

**Comment by gsarig** [comment]
Hi @frietboer And thanks for the feedback. Do you mean a style [like that](https://api.mapbox.com/styles/v1/mapbox-map-design/cl5utnuh1000n15mg8smuz168?access_token=pk.eyJ1IjoiZXhhbXBsZXMiLCJhIjoiY2lqbmpqazdlMDBsdnRva284cWd3bm11byJ9.V6Hg2oYJwMAxeoR9GEzkAA), for example, as described on the [Map Styles documentation](https://docs.mapbox.com/studio-manual/guides/map-styling/)?

**Comment by frietboer** [comment]
Yes, exactly this. This could be a nice option for even the less technical users.

**Comment by gsarig** [comment]
This is now implemented with [v2.7.2](https://github.com/gsarig/ootb-openstreetmap/releases/tag/2.7.2)
